# Generated by Django 2.0.9 on 2025-08-14 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('order_date', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coplaint', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('reply_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='own_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('OWN_SERVICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.own_service')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.CharField(max_length=200)),
                ('to_time', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('lattude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('year_of_experience', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='own_service',
            name='SERVICE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service'),
        ),
        migrations.AddField(
            model_name='own_service',
            name='WORKER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.worker'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='USERS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
        migrations.AddField(
            model_name='booking',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
        migrations.AddField(
            model_name='booking',
            name='own_SERVICE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.own_service'),
        ),
    ]
