# Generated by Django 2.0.9 on 2025-08-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='coplaint',
            new_name='complaint',
        ),
    ]
