# Generated by Django 2.0.9 on 2025-08-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250814_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='WORKER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.worker'),
            preserve_default=False,
        ),
    ]
