# Generated by Django 2.0.9 on 2025-09-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20250912_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_status',
        ),
    ]
