# Generated by Django 2.0.9 on 2025-09-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_service_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
