# Generated by Django 2.0.9 on 2025-09-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_service_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_status',
        ),
    ]
