# Generated by Django 2.0.9 on 2025-09-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_service_service_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='own_SERVICE',
            new_name='OWN_SERVICE',
        ),
    ]
