# Generated by Django 2.0.9 on 2025-09-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_service_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
